server:
  port: 8989
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8989/eureka/
    fetch-registry: false
    register-with-eureka: false
